version: "3"

services:
    client:
        build: ./client
        environment:
            - REACT_APP_PORT=3000
        expose:
            - 3000
        ports:
            - 3000:3000
        volumes:
            - ./client
            - ./client/public
        command: npm run start
